# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5344b3bec4926c32c79abb61f58b86fc1f59c6ee557c5bb69a32312b0974b9f4f7c1826e170632d0fe5b62a72c6f54120de05ab3bc58f77df971018bdbc01115

test:
  secret_key_base: 2ed87d6ddece751360edd8dd1900da79d87bfa61d2ee876b8afc65534bf414d8233fbef16c78b245898eea9f4e1e13932c77bbd9e92f76e80596d72fe4713662

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
